# Generated by Django 4.0.3 on 2022-04-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
