# Generated by Django 4.0.3 on 2022-04-04 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learnApp', '0004_subject_workspace_workspace_host_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-workspace_lastupdated', '-workspace_created']},
        ),
        migrations.AddField(
            model_name='workspace',
            name='workspace_lecturers',
            field=models.ManyToManyField(blank=True, related_name='lecturers', to=settings.AUTH_USER_MODEL),
        ),
    ]
