# Generated by Django 4.0.4 on 2022-05-24 08:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0005_alter_workspace_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_body',
            field=tinymce.models.HTMLField(),
        ),
    ]
