# Generated by Django 4.0.4 on 2022-05-24 11:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0010_alter_message_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
