# Generated by Django 4.0.4 on 2022-05-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0011_alter_message_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_body',
            field=models.TextField(),
        ),
    ]
